---
title: CV
---

## Academic positions

### University of Klagenfurt

since 2025 | Senior Scientist at the Department of Psychology, Section of Research Methods with [Ao. Univ.-Prof. Rainer W. Alexandrowicz](https://www.aau.at/en/team/alexandrowicz-rainer/) 

### Catholic University of Eichstätt-Ingolstadt

2024 - 2025 | Substitute professor at the [Chair of General Psychology](https://www.ku.de/en/ppf/psychologie/psychology6)

### Rhine-Waal-University of the Applied Sciences

2023 - 2025 | Wissenschaftlicher Mitarbeiter at the [Faculty of Society and Economics](https://www.hochschule-rhein-waal.de/en/faculties/society-and-economics)

### Catholic University of Eichstätt-Ingolstadt

2016 - 2023 | Akademischer Rat auf Zeit at the [Professorship for General Psychology II](https://www.ku.de/ppf/psychologie/psychologie2) with [Prof. Michael Zehetleitner](https://www.ku.de/ppf/psychologie/psychologie2/mitarbeitende/zehetleitner)<br />
2015 - 2016 | Wissenschaftlicher Mitarbeiter ibid.

### Ludwig-Maximilians-Universität München
2012 - 2015 | Wissenschaftlicher Mitarbeiter the [Chair of General and Experimental Psychology](https://www.psy.lmu.de/exp) with [Prof. Hermann Müller](https://www.psy.lmu.de/exp/people/prof/mueller/)

## Education

### Catholic University of Eichstädt-Ingolstadt
2021 - 2024 | Habilitation + Venia Legendi in Psychology ([Yearly award for the best Habilitation at the  Catholic University of Eichstädt-Ingolstadt](https://www.ku.de/die-ku/profil/universitaetspreise/preistraeger-2024/beste-habilitation))

### Ludwig-Maximilians-Universität München
2012 – 2016	|  PhD in Systemic Neurosciences (final grade: ‘very good’)<br />
2011 – 2012	|  M. Sc. in Neuro-cognitive Psychology (final grade: ‘excellent’)<br />
2010 - 2011	|  B. Sc. in Neuro-cognitive Psychology (final grade: ‘excellent’)<br />
2007 – 2011	|  Intermediate diploma in Psychology (final grade: ‘very good’)<br />




