---
title: Publications
---

## Pre-prints

Fung, H., Shekhar, M., Xue, K., Rausch, M., & Rahnev, D. (2025). Similarities and differences in the effects of different stimulus manipulations on accuracy and confidence. PsyArXiv. doi:10.31234/osf.io/b7kru_v1 \| [pre-print](https://osf.io/preprints/psyarxiv/b7kru_v1)

Short, C. A., Breznau, N., Bruntsch, M., Burkhardt, M., Busch, N., Cesnaite, E., Frank, M., Gießing, C., Krähmer, D., Kristanto, D., Lonsdorf, T., Neuendorf, C., Nguyen, H. H. V., Rausch, M., Schmalz, X., Schneck, A., Tabakci, C., & Hildebrandt, A. (2025). Multi-curious: A Multi-Disciplinary Guide to Multiverse Analysis. MetaArXiv. doi:10.31222/osf.io/4yzeh_v1 \| [pre-print](https://doi.org/10.31222/osf.io/4yzeh_v1)

Hellmann, S., Zehetleitner, M., & Rausch, M. (2024). dynConfiR: The R package for sequential sampling models of decision confidence. PsyArXiv. doi:10.31234/osf.io/e354s \| [pre-print](https://doi.org/10.31234/osf.io/e354s){target="_blank"} \| [development version of the package](https://github.com/SeHellmann/dynConfiR){target="_blank"} \| [released version of the package](https://cran.r-project.org/web/packages/dynConfiR/index.html){target="_blank"}

## Publications in peer-reviewed journals

Rausch, M., Meyen, S. & Hellmann, S. (2025). StatConfR: An R Package for Static Models of Decision Confidence and Metacognition. **Journal of Open Source Software**, 10(106), 6966. doi:10.21105/joss.06966 \| [full text](Rausch%20(2025)%20StatConfR.pdf){target="_blank"} \| [development version of the package](https://github.com/ManuelRausch/StatConfR){target="_blank"} \| [released version of the package](https://cran.r-project.org/web/packages/statConfR/index.html){target="_blank"}

Röseler, L., Kaiser, L., Doetsch, C., Klett, N., Seida, C., Schütz, A., Aczel, B., Adelina, N., Agostini, V., Alarie, S., Albayrak-Aydemir, N., Aldoh, A., Al-Hoorie, A. H., Azevedo, F., Baker, B. J., Barth, C. L., Beitner, J., Brick, C., Brohmer, H., … Rausch, M., … Zhang, Y. (2024). The Replication Database: Documenting the Replicability of Psychological Science. **Journal of Open Psychology Data**, 12(8), 1–23. doi:10.5334/jopd.101 \| [full text from publisher](https://openpsychologydata.metajnl.com/articles/101/files/66e18fdc5e1b7.pdf){target="_blank"} \| [data](https://osf.io/9r62x/){target="_blank"} \| [ShinyApp](https://metaanalyses.shinyapps.io/replicationdatabase/){target="_blank"}

Mushtaq, F., Welke, D., Gallagher, A., Pavlov Y. G., Kouara, L., Bosch-Bayard, J., van den Bosch J. J. F., Arvaneh, M., Bland A. R., Chaumon, M., Borck, C., He, X., Luck, S. J., Machizawa, M. G., Pernet, C., Puce, A., Segalowitz, S., Rogers, C., Awais, M., ... Rausch, M., … Valdez-Sosa, P. (2024). One hundred years of EEG for brain and behaviour research. **Nature Human Behaviour**, 8, 1437–1443. doi:10.1038/s41562-024-01941-5 \| [full text from publisher](https://t.co/2TvToy4uCi){target="_blank"} \| [data and code](https://osf.io/qv38p/){target="_blank"}

Hellmann, S., Zehetleitner, M., & Rausch, M. (2024). Confidence is influenced by evidence accumulation time in dynamical decision models. **Computational Brain & Behavior**, 7, 287 – 313. doi:10.1007/s42113-024-00205-9 \| [full text from publisher](https://link.springer.com/content/pdf/10.1007/s42113-024-00205-9.pdf){target="_blank"} \| [data and code](https://github.com/SeHellmann/MaterialsTimeInConfidence){target="_blank"}

Rausch, M., Hellmann, S., & Zehetleitner, M. (2023). Measures of metacognitive efficiency across cognitive models of decision confidence. **Psychological Methods**. doi:10.1037/met0000634 \| [accepted author manuscript](Rausch%20(2023)%20Accepted%20author%20manuscript.pdf){target="_blank"} \| [data and code](https://osf.io/72uds/){target="_blank"}

Rausch, M., & Zehetleitner, M. (2023). Evaluating false positive rates of standard and hierarchical measures of metacognitive accuracy. **Metacognition & Learning**, 18, 863--889. doi:10.1007/s11409-023-09353-y \| [full text](Rausch%20(2023)%20Hierarchical%20bootstraping%20metacognition.pdf){target="_blank"} \| [simulated data and code](https://osf.io/4pfrs){target="_blank"}

Hellmann, S., Zehetleitner, M., & Rausch, M. (2023). Simultaneous modeling of choice, confidence, and response time in visual perception. **Psychological Review**, 130(6), 1521-1543. doi:10.1037/rev0000411 \| [accepted author manuscript](Hellmann%20(2023)%20Accepted%20Author%20Manuscript.pdf){target="_blank"} \| [data and code](https://github.com/SeHellmann/SeqSamplingConfidenceModels){target="_blank"}

Rausch, M., Hellmann, S., & Zehetleitner, M. (2021). Modelling visibility judgments using models of decision confidence. **Attention, Perception, and Psychophysics**, 83(8), 3311-3336. doi:10.3758/s13414-021-02284-3 \| [full text](Rausch%20(2021)%20Modelling%20visibility%20judgments.pdf){target="_blank"} \| [data and code](https://osf.io/gfkta/){target="_blank"}

Rausch, M., Zehetleitner, M., Steinhauser, M., & Maier, M. E. (2020). Cognitive modelling reveals distinct electrophysiological markers of decision confidence and error monitoring. **NeuroImage**, 218, 116963. doi:10.1016/j.neuroimage.2020.116963 \| [full text](Rausch%20(2020)%20Distinct%20EEG%20correlates%20of%20confidence%20and%20error%20monitoring.pdf){target="_blank"} \| [data and code](https://osf.io/93weg/){target="_blank"}

Rahnev, D., Desender, K., Lee, A. L. F., Adler, W. T., Aguilar-Lleyda, D., Akdoğan, B., Arbuzova, P., Atlas, L. Y., Balcı, F., Bang, J. W., Bègue, I., Birney, D. P., Brady, T. F., Calder-Travis, J., Chetverikov, A., Clark, T. K., Davranche, K., Denison, R. N., ... Rausch, M., ... Zylberberg, A. (2020). The Confidence Database. **Nature Human Behaviour**, 4, 317--325. doi:10.1038/s41562-019-0813-1 \| [full text from publisher](https://rdcu.be/b232g){target="_blank"} \| [data and code](https://osf.io/s46pr){target="_blank"}

Rausch, M., & Zehetleitner, M. (2019). The folded X-pattern is not necessarily a statistical signature of decision confidence. **PLoS Computational Biology**, 15(10), e1007456. doi:10.1371/journal.pcbi.1007456 \| [full text](Rausch%20(2019)%20The%20folded%20X-pattern%20is%20not%20a%20statistical%20signature%20of%20confidence.pdf){target="_blank"} \| [data and code](https://osf.io/pfsqz/){target="_blank"}

Rausch, M., Hellmann, S., & Zehetleitner, M. (2018). Confidence in masked orientation judgments is informed by both evidence and visibility. **Attention, Perception, and Psychophysics**, 80(1), 134-154. doi:10.3758/s13414-017-1431-5 \| [full text from publisher](https://link.springer.com/content/pdf/10.3758/s13414-017-1431-5.pdf){target="_blank"} \| [data and code](https://osf.io/ty4h8){target="_blank"}

Schlagbauer, B., Rausch, M., Zehetleitner, M., Müller, H. J., & Geyer, T. (2018). Contextual cueing of visual search is associated with greater subjective experience of the search display configuration. **Neuroscience of Consciousness**, 4(1), niy001. doi:10.1093/nc/niy001 \| [full text](Schlagbauer%20(2018)%20Contextual%20cueing%20of%20visual%20search.pdf){target="_blank"} \| [data and code](https://osf.io/c25wb){target="_blank"}

Rausch, M., & Zehetleitner, M. (2017). Should metacognition be measured by logistic regression? **Consciousness and Cognition**, 49, 291--312. doi:10.1016/j.concog.2017.02.00 \| [accepted author manuscript](Rausch%20(2017)%20Logistic%20regression%20Accepted%20Author%20Manuscript.pdf){target="_blank"} \| [data and code](https://osf.io/72aqe/){target="_blank"}

Rausch, M., & Zehetleitner, M. (2016). Visibility is not equivalent to confidence in a low contrast orientation discrimination task. **Frontiers in Psychology**, 7, 591. doi:10.3389/fpsyg.2016.00591 \| [full text](Rausch%20(2016)%20Visibility%20is%20not%20equivalent%20to%20confidence.pdf){target="_blank"} \| [data and code](https://osf.io/vk6fe/){target="_blank"}

Rausch, M., Müller, H. J., & Zehetleitner, M. (2015). Metacognitive sensitivity of subjective reports of decisional confidence and visual experience. **Consciousness and Cognition**, 35, 192-205. doi:10.1016/j.concog.2015.02.011 \| [accepted author manuscript](Rausch%20(2015)%20Metacognitive%20sensitivity%20Accepted%20Author%20Manuscript.pdf){target="_blank"}

Rausch, M., & Zehetleitner, M. (2014). A comparison between a visual analogue scale and a four point scale as measures of conscious experience of motion. **Consciousness and Cognition**, 28(1), 126-140. doi:10.1016/j.concog.2014.06.012 \| [accepted author manuscript](Rausch%20(2014)%20VAS%20vs%20PAS%20Accepted%20Author%20Manuscript.pdf){target="_blank"}

Zehetleitner, M., & Rausch, M. (2013). Being confident without seeing: What subjective measures of visual consciousness are about. **Attention, Perception, and Psychophysics**, 75(7), 1406-1426. doi:10.3758/s13414-013-0505-2 \| [full text from publisher](https://link.springer.com/content/pdf/10.3758/s13414-013-0505-2.pdf){target="_blank"}
